server:
  port: 8082

spring:
  application:
    name: processing
  datasource:
    url: jdbc:mysql://processing-mysql:3307/processing_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: kafka:29092
    acks: all
    retries: 3
    consumer:
      group-id: processing-group
      auto-offset-reset: earliest
      retry_backoff_ms: 3000
      topic: order_topic

logging:
  level:
    root: INFO

resilience4j:
  circuitbreaker:
    instances:
      processingService:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
  ratelimiter:
    instances:
      processingService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true